name: CountryRoads
main: games.skweekychair.countryroads.CountryRoadsPlugin
version: 1.3
commands:
  addhome:
    description: add a new home at current locatin with name
    usage: /<command> [name]
    permission: countryroads.addhome
  home:
    description: go to home name default or specified by name
    usage: /<command> (name)
    permission: countryroads.home
  delhome:
    description: delete home specified by name, and optionally if you have manageotherhomes permission, the home owned by player
    usage: /<command> [name] (player)
    permission: countryroads.delhome
permissions:
  countryroads.addhome:
    default: true
  countryroads.home:
    default: true
  countryroads.delhome:
    default: true
  countryroads.manageotherhomes:
    default: op